name: Deploy bundle to S3 staging

on:
  repository_dispatch:
    types: [deploy]

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_USERNAME: actions_bot
  SLACK_CHANNEL: slack_bot
  SLACK_ICON: https://avatars.slack-edge.com/2022-02-26/3186911646272_22c66c95bf52ed05d10a_512.png

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Install Dependencies
        run: yarn
        working-directory: ./apps/react-webpack

      - name: Build
        run: yarn build:staging
        working-directory: ./apps/react-webpack

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: >
          aws s3 cp --recursive
          apps/react-webpack/dist s3://monofront-static/staging
          --exclude "*"
          --include "*.bundle.js"
          --region ap-northeast-1
          --acl public-read
          --cache-control "public, max-age=31536000"
          --metadata-directive REPLACE
          --metadata surrogate-key="apps react-webpack ${{ github.event.client_payload.ref }}"

      - name: Slack Notification on Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Deploy Success
          SLACK_COLOR: good
          SLACK_MESSAGE: ${{ github.event.client_payload.ref }}ブランチのデプロイが完了しました

      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Deploy Failure
          SLACK_COLOR: danger
          SLACK_MESSAGE: ${{ github.event.client_payload.ref }}ブランチのデプロイに失敗しました
