name: Deploy bundle to S3

on:
  push:
    branches:
      - main
    paths:
      - apps/app1/**

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: yarn
        working-directory: ./apps/app1

      - name: Build
        run: yarn build:production
        working-directory: ./apps/app1

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: >
          aws s3 cp --recursive
          apps/app1/dist s3://monofront-static
          –-include "*.bundle.js"
          --region ap-northeast-1
          --cache-control "public, max-age=31536000"
          --metadata-directive REPLACE
          --metadata x-amz-meta-surrogate-key="apps app1"
