on:
  pull_request:

permissions:
  pull-requests: write  # Required permission for commenting in PR

jobs:
  analysis:
    name: Analysis bundle files
    runs-on: ubuntu-latest

    steps:
      - name: Analysis
        uses: apple-yagi/bundle-analysis@v1
        with:
          out_dir: "./apps/react-webpack/dist" # Output directory for build
          ext: "bundle.js|chunk.js" # If specifying multiple extension, "js|css"
          github_token: ${{secrets.GITHUB_TOKEN}}
