name: React Webpack CI

on:
  pull_request:

permissions:
  pull-requests: write  # Required permission for commenting in PR

jobs:
  analysis:
    name: Analysis bundle files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Install & Build
        run: yarn --frozen-lock && yarn build:production
        working-directory: ./apps/react-webpack

      - name: Analysis
        uses: apple-yagi/filesize-analysis@v1
        with:
          out_dir: "./apps/react-webpack/dist" # Output directory for build
          ext: "bundle.js|chunk.js" # If specifying multiple extension, "js|css"
          build_cmd: "cd ./apps/react-webpack && yarn build:production"
          github_token: ${{secrets.GITHUB_TOKEN}}
